version: '3.8'

services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: runner-app-expo
    user: root
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "8081:8081"   # Metro bundler
      - "19000:19000" # Expo Go app
      - "19001:19001" # Expo manifest server
      - "19002:19002" # Expo Developer Tools
    command: >
      bash -c "npm install && 
               chown -R developer:developer /app/node_modules && 
               su developer -c 'npm start -- --lan'"
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - expo-network

networks:
  expo-network:
    driver: bridge

volumes:
  node_modules:
    driver: local 